apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: ccteam4acr.azurecr.io/customer
          ports:
            - containerPort: 8083
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /customers
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /customers
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          env:
            - name: EMBED_TOMCAT_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: spring-dev
                  key: JAVA_OPTS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-dev
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-dev
                  key: DB_PASS