apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagement
  labels:
    app: customermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagement
  template:
    metadata:
      labels:
        app: customermanagement
    spec:
      containers:
        - name: customermanagement
          image: username/customermanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5